version: '2.1'

services:
  onlinebanking:
    image: onlinebanking
    build: .
    links:
      - db
    ports:
      - 8080:8080

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_HOST: test-database-1.cft4pyst2fds.ap-southeast-1.rds.amazonaws.com
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: onlinebanking
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro